import React, { createContext, useContext, useState, ReactNode } from 'react';
import type { Language } from '@/types';

/* ─── translations ─── */
const T = {
  en: {
    home:'Home', schools:'Schools', students:'Students', fees:'Fees',
    expenses:'Expenses', reports:'Reports', staff:'Staff', settings:'Settings',
    totalSchools:'Total Schools', totalStudents:'Total Students',
    paidStudents:'Paid Students', unpaidStudents:'Unpaid Students',
    totalIncome:'Total Income', totalExpenses:'Total Expenses', netProfit:'Net Profit',
    search:'Search', add:'Add', edit:'Edit', delete:'Delete', save:'Save', cancel:'Cancel',
    name:'Name', phone:'Phone', address:'Address', amount:'Amount', date:'Date',
    note:'Note', type:'Type', role:'Role', salary:'Salary', school:'School',
    month:'Month', student:'Student', status:'Status', active:'Active',
    archived:'Archived', paid:'Paid', unpaid:'Unpaid', grade:'Grade',
    parentName:'Parent Name', parentPhone:'Parent Phone',
    discountType:'Discount Type', discountValue:'Discount Value',
    entryDate:'Entry Date', idNumber:'ID Number', schoolName:'School Name',
    addSchool:'Add School', editSchool:'Edit School', deleteSchool:'Delete School',
    addStudent:'Add Student', editStudent:'Edit Student',
    archive:'Archive', restore:'Restore',
    addFee:'Add Fee', editFee:'Edit Fee', feeType:'Fee Type',
    tuition:'Tuition', transportation:'Transportation', registration:'Registration', otherFee:'Other (Custom)',
    customFeeLabel:'Custom Fee Name',
    finalAmount:'Final Amount', billNumber:'Bill Number', discount:'Discount',
    addExpense:'Add Expense', editExpense:'Edit Expense',
    category:'Category', description:'Description', personName:'Person Name',
    salaryExp:'Salary', electricity:'Electricity', rent:'Rent',
    maintenance:'Maintenance', supplies:'Supplies', other:'Other',
    addStaff:'Add Staff', editStaff:'Edit Staff',
    teacher:'Teacher', guard:'Guard', adminStaff:'Admin Staff',
    cleaner:'Cleaner', driver:'Driver', customRole:'Custom Role',
    exitDate:'Exit Date', deactivate:'Deactivate', reactivate:'Reactivate',
    paySalary:'Pay Salary', totalPaid:'Total Paid', paymentHistory:'Payment History',
    none:'None', percentage:'Percentage', free:'Free',
    exportPdf:'Export PDF', exportCsv:'Export CSV', printReport:'Print Report',
    monthlyReport:'Monthly Report', dashboard:'Dashboard',
    filterBySchool:'Filter by School', filterByClass:'Filter by Class',
    allSchools:'All Schools', allClasses:'All Classes', noData:'No data available',
    confirm:'Are you sure?', deleteConfirm:'This action cannot be undone.',
    receipt:'Receipt', paymentDate:'Payment Date', downloadPdf:'Download PDF',
    whatsappReminder:'WhatsApp Reminder', darkMode:'Dark Mode', language:'Language',
    more:'More', staffMember:'Staff Member', archivedStudents:'Archived Students',
    activeStudents:'Active Students', income:'Income', profit:'Profit',
    allCategories:'All Categories', customCategory:'Custom Category',
    grades:'Grades', section:'Section', addGrade:'Add Grade', manageGrades:'Manage Grades',
    gradeLabel:'Grade', sectionLabel:'Section', noGrades:'No grades defined',
    monthlyBreakdown:'Monthly Breakdown', unpaidFees:'Unpaid Fees', estimated:'Estimated',
    monthly:'Monthly', total:'Total', importExcel:'Import Excel', rows:'rows',
    quarterly:'Quarterly', yearly:'Yearly', custom:'Custom', period:'Period',
    fromDate:'From', toDate:'To', allTime:'All Time', q1:'Q1 (Hamal-Jawza)',
    q2:'Q2 (Saratan-Sunbula)', q3:'Q3 (Mizan-Qaws)', q4:'Q4 (Jadi-Hoot)',
    login:'Login', email:'Email', password:'Password', logout:'Logout',
    forgotPassword:'Forgot Password?', enterEmailFirst:'Enter your email first',
    resetEmailSent:'Password reset link sent to your email',
    resetPassword:'Reset Password', newPassword:'New Password', updatePassword:'Update Password',
    passwordUpdated:'Password updated successfully',
    resetApp:'Reset App', resetAppConfirm:'This will delete ALL data and accounts. Enter master passcode to confirm.',
    resetSuccess:'App reset successfully', resetting:'Resetting...',
    admins:'Admins', addAdmin:'Add Admin', owner:'Owner', noAccess:'Access denied',
    initialSetup:'Initial Setup', setupDescription:'Create the owner account to get started',
    masterPasscode:'Master Passcode', confirmPasscode:'Confirm Passcode',
    passcodeHint:'Save this passcode — it is needed to transfer ownership later',
    passcodeMinLength:'Passcode must be at least 6 characters',
    passcodeMismatch:'Passcodes do not match', createOwner:'Create Owner Account',
    transferOwnership:'Transfer Ownership', newOwner:'New Owner',
    currentPasscode:'Current Master Passcode', newPasscode:'New Master Passcode (optional)',
    checkingSetup:'Checking setup...', changePassword:'leave blank to keep',
    editAdmin:'Edit Admin',
    printSelected:'Print Selected',
    selectAll:'Select All',
    combinedReceipt:'Combined Receipt',
    grandTotal:'Grand Total',
    items:'Items',
    monthlyFee:'Monthly Fee',
    exportExcel:'Export Excel',
    studentsCount:'Students',
    staffPayments:'Staff Payments',
    paymentRecords:'Payment Records',
    gradeSection:'Grade/Section',
  },
  da: {
    home:'خانه', schools:'مکاتب', students:'شاگردان', fees:'فیس‌ها',
    expenses:'مصارف', reports:'گزارشات', staff:'کارمندان', settings:'تنظیمات',
    totalSchools:'مجموع مکاتب', totalStudents:'مجموع شاگردان',
    paidStudents:'پرداخت شده', unpaidStudents:'پرداخت نشده',
    totalIncome:'مجموع عواید', totalExpenses:'مجموع مصارف', netProfit:'سود خالص',
    search:'جستجو', add:'اضافه', edit:'ویرایش', delete:'حذف', save:'ذخیره', cancel:'لغو',
    name:'نام', phone:'تلفن', address:'آدرس', amount:'مبلغ', date:'تاریخ',
    note:'یادداشت', type:'نوع', role:'وظیفه', salary:'معاش', school:'مکتب',
    month:'ماه', student:'شاگرد', status:'وضعیت', active:'فعال',
    archived:'آرشیف', paid:'پرداخت شده', unpaid:'پرداخت نشده', grade:'صنف',
    parentName:'نام والدین', parentPhone:'تلفن والدین',
    discountType:'نوع تخفیف', discountValue:'مقدار تخفیف',
    entryDate:'تاریخ شمولیت', idNumber:'شماره تذکره', schoolName:'نام مکتب',
    addSchool:'اضافه کردن مکتب', editSchool:'ویرایش مکتب', deleteSchool:'حذف مکتب',
    addStudent:'اضافه کردن شاگرد', editStudent:'ویرایش شاگرد',
    archive:'آرشیف', restore:'بازگردانی',
    addFee:'اضافه کردن فیس', editFee:'ویرایش فیس', feeType:'نوع فیس',
    tuition:'تعلیمی', transportation:'ترانسپورت', registration:'ثبت‌نام', otherFee:'سایر (سفارشی)',
    customFeeLabel:'نام فیس سفارشی',
    finalAmount:'مبلغ نهایی', billNumber:'شماره بل', discount:'تخفیف',
    addExpense:'اضافه کردن مصرف', editExpense:'ویرایش مصرف',
    category:'کتگوری', description:'توضیحات', personName:'نام شخص',
    salaryExp:'معاش', electricity:'برق', rent:'کرایه',
    maintenance:'ترمیمات', supplies:'لوازم', other:'سایر',
    addStaff:'اضافه کردن کارمند', editStaff:'ویرایش کارمند',
    teacher:'استاد', guard:'محافظ', adminStaff:'کارمند اداری',
    cleaner:'نظافتچی', driver:'دریور', customRole:'وظیفه سفارشی',
    exitDate:'تاریخ خروج', deactivate:'غیرفعال', reactivate:'فعال‌سازی',
    paySalary:'پرداخت معاش', totalPaid:'مجموع پرداخت', paymentHistory:'تاریخچه پرداخت',
    none:'هیچ', percentage:'فیصدی', free:'رایگان',
    exportPdf:'دانلود PDF', exportCsv:'دانلود CSV', printReport:'چاپ گزارش',
    monthlyReport:'گزارش ماهانه', dashboard:'داشبورد',
    filterBySchool:'فلتر مکتب', filterByClass:'فلتر صنف',
    allSchools:'همه مکاتب', allClasses:'همه صنف‌ها', noData:'معلومات موجود نیست',
    confirm:'آیا مطمئن هستید؟', deleteConfirm:'این عمل قابل بازگشت نیست.',
    receipt:'رسید', paymentDate:'تاریخ پرداخت', downloadPdf:'دانلود PDF',
    whatsappReminder:'یادآوری واتساپ', darkMode:'حالت تاریک', language:'زبان',
    more:'بیشتر', staffMember:'کارمند', archivedStudents:'شاگردان آرشیف',
    activeStudents:'شاگردان فعال', income:'عواید', profit:'سود',
    allCategories:'همه کتگوری‌ها', customCategory:'کتگوری سفارشی',
    grades:'صنوف', section:'بخش', addGrade:'اضافه کردن صنف', manageGrades:'مدیریت صنوف',
    gradeLabel:'صنف', sectionLabel:'بخش', noGrades:'صنفی تعریف نشده',
    monthlyBreakdown:'تفکیک ماهانه', unpaidFees:'فیس‌های پرداخت نشده', estimated:'تخمینی',
    monthly:'ماهانه', total:'مجموع', importExcel:'وارد کردن اکسل', rows:'ردیف',
    quarterly:'ربع‌وار', yearly:'سالانه', custom:'سفارشی', period:'دوره',
    fromDate:'از تاریخ', toDate:'تا تاریخ', allTime:'همه',  q1:'ربع ۱ (حمل-جوزا)',
    q2:'ربع ۲ (سرطان-سنبله)', q3:'ربع ۳ (میزان-قوس)', q4:'ربع ۴ (جدی-حوت)',
    login:'ورود', email:'ایمیل', password:'رمز عبور', logout:'خروج',
    forgotPassword:'رمز عبور را فراموش کردید؟', enterEmailFirst:'اول ایمیل خود را وارد کنید',
    resetEmailSent:'لینک بازنشانی رمز به ایمیل شما ارسال شد',
    resetPassword:'بازنشانی رمز', newPassword:'رمز جدید', updatePassword:'تغییر رمز',
    passwordUpdated:'رمز عبور با موفقیت تغییر کرد',
    resetApp:'بازنشانی برنامه', resetAppConfirm:'تمام داده‌ها و حساب‌ها حذف خواهد شد. رمز اصلی را وارد کنید.',
    resetSuccess:'برنامه با موفقیت بازنشانی شد', resetting:'در حال بازنشانی...',
    admins:'مدیران', addAdmin:'اضافه کردن مدیر', owner:'مالک', noAccess:'دسترسی ندارید',
    initialSetup:'تنظیمات اولیه', setupDescription:'حساب مالک را ایجاد کنید تا شروع کنید',
    masterPasscode:'رمز اصلی', confirmPasscode:'تأیید رمز اصلی',
    passcodeHint:'این رمز را ذخیره کنید — برای انتقال مالکیت لازم است',
    passcodeMinLength:'رمز باید حداقل ۶ حرف باشد',
    passcodeMismatch:'رمزها مطابقت ندارند', createOwner:'ایجاد حساب مالک',
    transferOwnership:'انتقال مالکیت', newOwner:'مالک جدید',
    currentPasscode:'رمز اصلی فعلی', newPasscode:'رمز اصلی جدید (اختیاری)',
    checkingSetup:'بررسی تنظیمات...', changePassword:'خالی بگذارید تا تغییر نکند',
    editAdmin:'ویرایش مدیر',
    printSelected:'چاپ انتخاب شده',
    selectAll:'انتخاب همه',
    combinedReceipt:'رسید مشترک',
    grandTotal:'مجموع کل',
    items:'موارد',
    monthlyFee:'فیس ماهانه',
    exportExcel:'دانلود اکسل',
    studentsCount:'شاگردان',
    staffPayments:'پرداخت‌های کارمندان',
    paymentRecords:'سوابق پرداخت',
    gradeSection:'صنف/بخش',
  },
  ps: {
    home:'کور', schools:'ښوونځي', students:'زدکونکي', fees:'فیسونه',
    expenses:'لګښتونه', reports:'راپورونه', staff:'کارکوونکي', settings:'ترتیبات',
    totalSchools:'ټول ښوونځي', totalStudents:'ټول زدکونکي',
    paidStudents:'ورکړل شوي', unpaidStudents:'نه ورکړل شوي',
    totalIncome:'ټول عواید', totalExpenses:'ټول لګښتونه', netProfit:'خالص ګټه',
    search:'لټون', add:'اضافه', edit:'سمون', delete:'لرې کول', save:'خوندي', cancel:'لغوه',
    name:'نوم', phone:'تلیفون', address:'پته', amount:'مقدار', date:'نېټه',
    note:'یادونه', type:'ډول', role:'دنده', salary:'معاش', school:'ښوونځی',
    month:'میاشت', student:'زدکونکی', status:'حالت', active:'فعال',
    archived:'آرشیف', paid:'ورکړل شوی', unpaid:'نه ورکړل شوی', grade:'ټولګی',
    parentName:'د والدینو نوم', parentPhone:'د والدینو تلیفون',
    discountType:'د تخفیف ډول', discountValue:'د تخفیف مقدار',
    entryDate:'د شمولیت نېټه', idNumber:'د تذکرې شمېره', schoolName:'د ښوونځي نوم',
    addSchool:'ښوونځی اضافه', editSchool:'ښوونځی سمول', deleteSchool:'ښوونځی لرې کول',
    addStudent:'زدکونکی اضافه', editStudent:'زدکونکی سمول',
    archive:'آرشیف', restore:'بیرته راوستل',
    addFee:'فیس اضافه', editFee:'فیس سمول', feeType:'د فیس ډول',
    tuition:'تعلیمي', transportation:'ترانسپورت', registration:'ثبت‌نام', otherFee:'نور (خپل)',
    customFeeLabel:'د خپل فیس نوم',
    finalAmount:'وروستی مقدار', billNumber:'د بل شمېره', discount:'تخفیف',
    addExpense:'لګښت اضافه', editExpense:'لګښت سمول',
    category:'کتګوري', description:'تشریح', personName:'د شخص نوم',
    salaryExp:'معاش', electricity:'برېښنا', rent:'کرایه',
    maintenance:'ترمیم', supplies:'سامان', other:'نور',
    addStaff:'کارکوونکی اضافه', editStaff:'کارکوونکی سمول',
    teacher:'ښوونکی', guard:'ساتونکی', adminStaff:'اداري کارکوونکی',
    cleaner:'صفاکار', driver:'موټروان', customRole:'خپله دنده',
    exitDate:'د وتلو نېټه', deactivate:'غیرفعال', reactivate:'فعالول',
    paySalary:'معاش ورکول', totalPaid:'ټول ورکړل شوي', paymentHistory:'د تادیاتو تاریخچه',
    none:'هیڅ', percentage:'سلنه', free:'وړیا',
    exportPdf:'PDF ډاونلوډ', exportCsv:'CSV ډاونلوډ', printReport:'راپور چاپ',
    monthlyReport:'میاشتنی راپور', dashboard:'ډشبورډ',
    filterBySchool:'د ښوونځي فلټر', filterByClass:'د ټولګي فلټر',
    allSchools:'ټول ښوونځي', allClasses:'ټول ټولګي', noData:'معلومات نشته',
    confirm:'ایا ډاډه یاست؟', deleteConfirm:'دا عمل بېرته نشي کیدای.',
    receipt:'رسید', paymentDate:'د تادیې نېټه', downloadPdf:'PDF ډاونلوډ',
    whatsappReminder:'واټساپ یادونه', darkMode:'تیاره حالت', language:'ژبه',
    more:'نور', staffMember:'کارکوونکی', archivedStudents:'آرشیف شوي زدکونکي',
    activeStudents:'فعال زدکونکي', income:'عواید', profit:'ګټه',
    allCategories:'ټولې کټګورۍ', customCategory:'خپله کټګوري',
    grades:'ټولګي', section:'برخه', addGrade:'ټولګی اضافه', manageGrades:'ټولګي اداره',
    gradeLabel:'ټولګی', sectionLabel:'برخه', noGrades:'ټولګی ندی ټاکل شوی',
    monthlyBreakdown:'میاشتني توضیحات', unpaidFees:'نه ورکړل شوي فیسونه', estimated:'اټکل شوی',
    monthly:'میاشتني', total:'ټول', importExcel:'اکسل واردول', rows:'ردۍ',
    quarterly:'ربعي', yearly:'کلنی', custom:'خپل', period:'دوره',
    fromDate:'له', toDate:'تر', allTime:'ټول', q1:'ربع ۱ (وری-غبرګولی)',
    q2:'ربع ۲ (چنګاښ-وږی)', q3:'ربع ۳ (تله-لیندۍ)', q4:'ربع ۴ (مرغومی-کب)',
    login:'ننوتل', email:'بریښنالیک', password:'پټنوم', logout:'وتل',
    forgotPassword:'پټنوم مو هیر شوی؟', enterEmailFirst:'لومړی خپل بریښنالیک ولیکئ',
    resetEmailSent:'د پټنوم بیاتنظیم لینک ستاسو بریښنالیک ته ولیږل شو',
    resetPassword:'پټنوم بیاتنظیم', newPassword:'نوی پټنوم', updatePassword:'پټنوم بدلول',
    passwordUpdated:'پټنوم په بریالیتوب سره بدل شو',
    resetApp:'اپلیکیشن بیاتنظیم', resetAppConfirm:'ټول معلومات او حسابونه به حذف شي. اصلي پټنوم دننه کړئ.',
    resetSuccess:'اپلیکیشن په بریالیتوب بیاتنظیم شو', resetting:'بیاتنظیمول...',
    admins:'مدیران', addAdmin:'مدیر اضافه کول', owner:'مالک', noAccess:'لاسرسی نشته',
    initialSetup:'لومړنۍ ترتیبات', setupDescription:'د مالک حساب جوړ کړئ ترڅو پیل وکړئ',
    masterPasscode:'اصلي پټنوم', confirmPasscode:'اصلي پټنوم تایید',
    passcodeHint:'دا پټنوم خوندي کړئ — د مالکیت لیږد لپاره اړین دی',
    passcodeMinLength:'پټنوم باید لږترلږه ۶ توري ولري',
    passcodeMismatch:'پټنومونه سره نه سمون خوري', createOwner:'د مالک حساب جوړول',
    transferOwnership:'د مالکیت لیږد', newOwner:'نوی مالک',
    currentPasscode:'اوسنی اصلي پټنوم', newPasscode:'نوی اصلي پټنوم (اختیاري)',
    checkingSetup:'ترتیبات چک کول...', changePassword:'خالي پرېږدئ ترڅو بدل نشي',
    editAdmin:'مدیر سمول',
    printSelected:'انتخاب شوي چاپ کول',
    selectAll:'ټول انتخاب',
    combinedReceipt:'ګډ رسید',
    grandTotal:'ټوله مجموعه',
    items:'توکي',
    monthlyFee:'میاشتني فیس',
    exportExcel:'اکسل ډاونلوډ',
    studentsCount:'زدکونکي',
    staffPayments:'د کارکوونکو تادیات',
    paymentRecords:'د تادیاتو سوابق',
    gradeSection:'ټولګی/برخه',
  },
} as const;

type TKey = keyof typeof T.en;

interface Ctx {
  lang: Language;
  setLang: (l: Language) => void;
  t: (k: TKey) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<Ctx | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => (localStorage.getItem('app-lang') as Language) || 'en');
  const t = (k: TKey) => (T[lang] as any)[k] || (T.en as any)[k] || k;
  const dir = lang === 'en' ? 'ltr' : 'rtl';
  const set = (l: Language) => { setLang(l); localStorage.setItem('app-lang', l); };
  return <LanguageContext.Provider value={{ lang, setLang: set, t, dir }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const c = useContext(LanguageContext);
  if (!c) throw new Error('useLanguage outside provider');
  return c;
};
